### ISSUE TITLE
Confusion in Readme around where to place the classpath for gms

### ISSUE THREAD

**Issue by dagostinelli** [pfieffer/GoogleLoginTest#2]
In the [README.md](https://raw.githubusercontent.com/pfieffer/GoogleLoginTest/master/README.md), it says

```
allprojects{
    // Google Sign In SDK (only required for Google Sign In)
    compile 'com.google.android.gms:play-services-auth:11.6.0'
}
```

But in the sample code, the `compile` directive is placed in the `buildscript`

https://github.com/pfieffer/GoogleLoginTest/blob/master/build.gradle

The README.md should instruct the user to put it in the buildscript.

**Comment by pfieffer** [comment]
Thanks. I will correct this.
